import type { PracticeQuestion } from "./types";

export const practiceQuestions: PracticeQuestion[] = [
  { id: "p01", level: "foundation", moduleId: "chart-model", format: "spot-overclaim", prompt: "Which statement overclaims?", choices: ["The Moon is at 6° Taurus.", "The Moon is in the ninth whole-sign house.", "This Moon guarantees residence abroad."], answer: 2, rubric: ["Separates coordinate, mapping and prediction."], explanation: "A specific life event cannot be guaranteed from one placement." },
  { id: "p02", level: "foundation", moduleId: "signs", format: "multiple-choice", prompt: "Mercury moves from fixed earth to movable fire. Which layer changes first?", choices: ["Mercury's core function", "Its style and operating conditions", "The ascendant"], answer: 1, rubric: ["Identifies sign as style."], explanation: "Mercury still processes and exchanges; pace and medium change." },
  { id: "p03", level: "foundation", moduleId: "houses", format: "short-reasoning", prompt: "The seventh house is empty. Name the next three checks.", answer: "sign, lord, aspects", rubric: ["Names sign", "Traces lord", "Checks incoming influence"], explanation: "Empty houses remain active through their sign, lord and relationships." },
  { id: "p04", level: "foundation", moduleId: "grahas", format: "spot-overclaim", prompt: "Improve: ‘Saturn in the fifth denies children.’", answer: "Saturn may introduce delay, responsibility or sustained effort in fifth-house topics; other factors and context are required.", rubric: ["Removes certainty", "Broadens fifth-house topics", "Requests corroboration"], explanation: "The original is deterministic and reduces the fifth house to one outcome." },
  { id: "p05", level: "foundation", moduleId: "lordship", format: "multiple-choice", prompt: "The tenth lord in the third most directly links…", choices: ["work with skills and communication", "home with inheritance", "relationships with retreat"], answer: 0, rubric: ["Maps both house fields."], explanation: "Lordship creates a structural connection, not a fixed profession." },
  { id: "p06", level: "foundation", moduleId: "condition", format: "rank-evidence", prompt: "Rank checks after noticing an exalted planet.", choices: ["house ownership", "house placement", "aspects/conjunctions", "declare success"], answer: [0,1,2,3], rubric: ["Keeps declaration last", "Includes agenda and context"], explanation: "Exaltation describes capacity, not automatically beneficial outcome." },
  { id: "p07", level: "foundation", moduleId: "dispositors", format: "short-reasoning", prompt: "Venus is in Gemini and Mercury in Taurus. Name the structure.", answer: "mutual reception or parivartana", rubric: ["Identifies closed exchange", "Does not call it automatically good"], explanation: "Each occupies the other’s sign; condition and house ownership remain relevant." },
  { id: "p08", level: "foundation", moduleId: "conjunctions", format: "multiple-choice", prompt: "Two planets share a sign at 1° and 29°. Best label?", choices: ["tight conjunction", "same-sign co-tenancy with wide separation", "unrelated"], answer: 1, rubric: ["Uses degree distance."], explanation: "They share sign context but are not tightly joined." },
  { id: "p09", level: "foundation", moduleId: "aspects", format: "multiple-choice", prompt: "Mars in House 4 has its eighth aspect on…", choices: ["House 11", "House 12", "House 8"], answer: 0, rubric: ["Counts occupied house as one."], explanation: "4→5(2)→6(3)→7(4)→8(5)→9(6)→10(7)→11(8)." },
  { id: "p10", level: "intermediate", moduleId: "repetition", format: "rank-evidence", prompt: "Rank evidence for a teaching theme.", choices: ["ninth lord in tenth", "Jupiter linked to second/tenth", "D10 repeats Jupiter emphasis", "a generic Sagittarius keyword"], answer: [0,1,2,3], rubric: ["Prioritises structural and independent evidence", "Leaves generic keyword last"], explanation: "Repeated independent structures deserve more weight than a broad association." },
  { id: "p11", level: "intermediate", moduleId: "natal-transit", format: "spot-overclaim", prompt: "Transit Jupiter enters the seventh. Which statement is safest?", choices: ["Marriage will occur.", "Partnership growth becomes one plausible theme; inspect natal seventh-house factors and active periods.", "Nothing can be said."], answer: 1, rubric: ["Conditional", "Requires natal and timing context"], explanation: "A transit activates possibilities; it does not force one event." },
  { id: "p12", level: "intermediate", moduleId: "responsible-synthesis", format: "short-reasoning", prompt: "Write a four-part synthesis template.", answer: "claim; supporting evidence; contradiction/alternative; timing and uncertainty", rubric: ["Claim", "Evidence", "Counter-evidence", "Timing/limits"], explanation: "Transparent synthesis includes both reasoning and boundaries." },
  { id: "p13", level: "intermediate", moduleId: "nakshatra", format: "multiple-choice", prompt: "Why does a nakshatra pada matter?", choices: ["It links the lunar mansion segment to a navamsha sign.", "It changes the planet’s longitude.", "It guarantees a profession."], answer: 0, rubric: ["Connects 3°20′ pada and D9."], explanation: "Each pada maps to one navamsha sign." },
  { id: "p14", level: "advanced", moduleId: "varga", format: "spot-overclaim", prompt: "A low-confidence birth time produces a D60 claim. What should the app do?", answer: "Warn or disable the claim and demonstrate sensitivity to small time changes.", rubric: ["Recognises time sensitivity", "Does not hide uncertainty"], explanation: "Fine divisional charts can change rapidly and require reliable birth time." },
  { id: "p15", level: "advanced", moduleId: "timing", format: "rank-evidence", prompt: "Order a timing analysis.", choices: ["natal promise", "dasha/subperiod", "slow transit repetition", "fast trigger", "specific event certainty"], answer: [0,1,2,3,4], rubric: ["Natal first", "Period before transit trigger", "Rejects certainty"], explanation: "Layer timing evidence from enduring structure to short activation." },
  { id: "p16", level: "advanced", moduleId: "yoga", format: "short-reasoning", prompt: "A software detector finds a raja-yoga candidate. What four checks follow?", answer: "exact rule, planet condition, cancellation/modification, active timing", rubric: ["Rule provenance", "Condition", "Counter-condition", "Timing"], explanation: "Detection is the beginning of reasoning, not the verdict." }
];
